export const IndustryTypes = [
  "Appliance Repair",
  "Banking & Insurance",
  "Carpentry",
  "Carpet Cleaning",
  "Catering",
  "Chimney Sweep Services",
  "Cleaning Services",
  "Coffee Maker Repair",
  "Commercial Cleaning",
  "Concrete",
  "Construction",
  "Delivery",
  "Demolition Contractor",
  "Dishwasher Repair",
  "Dog Walking",
  "Dryer Repair",
  "Drywall",
  "Electrical",
  "Electrical Contracting",
  "Electromechanical",
  "Elevator Services",
  "Energy & Utility",
  "Event Planning",
  "Excavation",
  "Fence Services",
  "Fire Safety",
  "Flooring",
  "Franchise Management",
  "Garage Door Services",
  "Gardening Services",
  "General Contracting",
  "HVAC",
  "Handyman",
  "Healthcare",
  "Homecare Services",
  "Installation Services",
  "Irrigation Services",
  "Janitorial Services",
  "Junk Removal",
  "Landscaping Services",
  "Lawn Care",
  "Lawn Mover Services",
  "Locksmith Services",
  "Logistics Services",
  "Maid Services",
  "Manufacturing",
  "Mechanical Contracting",
  "Microwave Repair",
  "Oil & Gas",
  "Oven and Stove Repair",
  "Painting",
  "Paving",
  "Pest Control",
  "Plumbing",
  "Pool Services",
  "Pressure Washing",
  "Property Maintenance",
  "Refrigerator Repair",
  "Reirrigation",
  "Remodeling",
  "Removals & Storage",
  "Residential Cleaning",
  "Residential Services",
  "Restoration",
  "Restoration Services",
  "Roofing",
  "Sales",
  "Security & Surveillance",
  "Snow Removal",
  "Spa Services",
  "Telecommunication",
  "Tiling",
  "Tree Care",
  "Washing Machine Repair",
  "Well Water Services",
  "Window Cleaning"
]
